const COMPLETE_BIN_CODE = /^[^-*|]+-[^-*|]+-[^-*|]+(?:-[^-*|]+)*$/;

/**
 * Convert an Autosav storage-label envelope to the Sentry bin code it carries.
 * Product, PO, SO and native Sentry barcodes pass through unchanged.
 */
export function normalizeScannedBarcode(rawValue = '') {
  const raw = String(rawValue || '')
    .replace(/[\r\n\s]+/g, '')
    .replace(/\\\*/g, '*')
    .trim();
  const separator = raw.includes('*') ? '*' : (raw.includes('|') ? '|' : '');
  if (!separator) return raw;

  const parts = raw.split(separator).map((part) => part.trim());
  const prefix = String(parts[0] || '').toUpperCase();
  if (prefix === 'ASL1') {
    const candidate = parts[2] || '';
    return COMPLETE_BIN_CODE.test(candidate) ? candidate : raw;
  }
  if (prefix === 'ASL2' && parts.length >= 5) {
    const addressParts = parts.slice(2, 5);
    if (addressParts.every(Boolean)) return addressParts.join('-');
  }
  return raw;
}

/**
 * Recognize the printable warehouse hierarchy labels generated by Admin.
 * These labels identify a navigation landmark, not an inventory-holding bin;
 * stock workflows still require scanning the exact bin label afterwards.
 */
export function parseWarehouseHierarchyBarcode(rawValue = '') {
  const raw = String(rawValue || '').replace(/[\r\n\s]+/g, '').trim();
  if (!raw) return null;

  const legacyRow = raw.match(/^ROW-(.+)$/i);
  if (legacyRow) {
    return {
      kind: 'AISLE',
      title: `CULOAR ${legacyRow[1]}`,
      message: 'Etichetă de culoar recunoscută. Pentru o operațiune de stoc, scanează apoi eticheta bin-ului exact.',
    };
  }

  const match = raw.match(/^(ZONE|AISLE|SHELF):(.+)$/i);
  if (!match) return null;
  const kind = match[1].toUpperCase();
  const parts = match[2].split(':').filter(Boolean);
  if (parts.length === 0) return null;

  if (kind === 'ZONE') {
    return {
      kind,
      title: `ZONĂ ${parts.join(' · ')}`,
      message: 'Etichetă de zonă recunoscută. Scanează eticheta culoarului, raftului sau bin-ului pentru locația exactă.',
    };
  }
  if (kind === 'AISLE') {
    return {
      kind,
      title: `CULOAR ${parts.at(-1)}`,
      message: `Zonă: ${parts.slice(0, -1).join(' · ') || '-'}\nPentru o operațiune de stoc, scanează apoi eticheta bin-ului exact.`,
    };
  }
  return {
    kind,
    title: `RAFT ${parts.at(-1)}`,
    message: `Zonă / culoar: ${parts.slice(0, -1).join(' · ') || '-'}\nPentru o operațiune de stoc, scanează apoi eticheta bin-ului exact.`,
  };
}
